sit:
  base_url: https://httpbin.org
  countries:
    br:
      timezone: America/Sao_Paulo
      supported_languages: pt_BR
      services:
        test-service:
          post:
            request_through_middleware_api: false
            auth_type: Bearer
            auth_token: access_token
            auth_method: post
            auth_url: https://fake-auth.example.com
            auth_grant_type: client_credentials
            auth_client_id: test-client
            auth_scope: openid
            auth_client_secret: test-secret
            versions:
              v1:
                value_stream_url: /post
                encoding_type: utf-8
                id_prefix: TEST
                amount_data_mass: 2
                template_name: null
                csv_data_source: null
                csv_strategy: null
                param_keys: "name:name,email:email"
                static_params: null
                multiple_request: false
                zip_payload: false
